using System;
using System.Collections.Generic;

namespace TMS.API.FastTruongNamModels
{
    public partial class AccessRight
    {
        public string UserName { get; set; }
        public bool ExpressBookSave { get; set; }
        public bool ExpressBookDelete { get; set; }
        public bool ExpressBookRead { get; set; }
        public bool ExpressProfitSave { get; set; }
        public bool ExpressProfitDelete { get; set; }
        public bool ExpressProfitRead { get; set; }
        public bool ExpressPaymentSave { get; set; }
        public bool ExpressPaymentRead { get; set; }
        public bool AirBookSave { get; set; }
        public bool AirBookDelete { get; set; }
        public bool AirBookRead { get; set; }
        public bool AirProfitSave { get; set; }
        public bool AirProfitDelete { get; set; }
        public bool AirProfitRead { get; set; }
        public bool AirPaymentSave { get; set; }
        public bool AirPaymentRead { get; set; }
        public bool AirImpBookSave { get; set; }
        public bool AirImpBookDelete { get; set; }
        public bool AirImpBookRead { get; set; }
        public bool AirImpProfitSave { get; set; }
        public bool AirImpProfitDelete { get; set; }
        public bool AirImpProfitRead { get; set; }
        public bool AirImpPaymentSave { get; set; }
        public bool AirImpPaymentRead { get; set; }
        public bool SeaLCLBookSave { get; set; }
        public bool SeaLCLBookDelete { get; set; }
        public bool SeaLCLBookRead { get; set; }
        public bool SeaLCLProfitSave { get; set; }
        public bool SeaLCLProfitDelete { get; set; }
        public bool SeaLCLProfitRead { get; set; }
        public bool SeaLLCLPaymentSave { get; set; }
        public bool SeaLLCLPaymentRead { get; set; }
        public bool SeaImpLCLBookSave { get; set; }
        public bool SeaImpLCLBookDelete { get; set; }
        public bool SeaImpLCLBookRead { get; set; }
        public bool SeaImpLCLProfitSave { get; set; }
        public bool SeaImpLCLProfitDelete { get; set; }
        public bool SeaImpLCLProfitRead { get; set; }
        public bool SeaLLCLImpPaymentSave { get; set; }
        public bool SeaLLCLImpPaymentRead { get; set; }
        public bool SeaFCLBookSave { get; set; }
        public bool SeaFCLBookDelete { get; set; }
        public bool SeaFCLBookRead { get; set; }
        public bool SeaFCLProfitSave { get; set; }
        public bool SeaFCLProfitDelete { get; set; }
        public bool SeaFCLProfitRead { get; set; }
        public bool SeaFLCLPaymentSave { get; set; }
        public bool SeaFLCLPaymentRead { get; set; }
        public bool? SeaFCLfixedCostRead { get; set; }
        public bool? SeaFCLfixedCostSave { get; set; }
        public bool? SeaFCLfixedCostDelete { get; set; }
        public bool SeaImpFCLBookSave { get; set; }
        public bool SeaImpFCLBookDelete { get; set; }
        public bool SeaImpFCLBookRead { get; set; }
        public bool SeaImpFCLProfitSave { get; set; }
        public bool SeaImpFCLProfitDelete { get; set; }
        public bool SeaImpFCLProfitRead { get; set; }
        public bool SeaFLCLImpPaymentSave { get; set; }
        public bool SeaFLCLImpPaymentRead { get; set; }
        public bool SeaConsoleBookSave { get; set; }
        public bool SeaConsoleBookDelete { get; set; }
        public bool SeaConsoleBookRead { get; set; }
        public bool SeaConsoleProfitSave { get; set; }
        public bool SeaConsoleProfitDelete { get; set; }
        public bool SeaConsoleProfitRead { get; set; }
        public bool SeaConsolePaymentSave { get; set; }
        public bool SeaConsolePaymentRead { get; set; }
        public bool SeaImpConsoleBookSave { get; set; }
        public bool SeaImpConsoleBookDelete { get; set; }
        public bool SeaImpConsoleBookRead { get; set; }
        public bool SeaImpConsoleProfitSave { get; set; }
        public bool SeaImpConsoleProfitDelete { get; set; }
        public bool SeaImpConsoleProfitRead { get; set; }
        public bool SeaImpConsolePaymentSave { get; set; }
        public bool SeaImpConsolePaymentRead { get; set; }
        public bool LogisticsBookSave { get; set; }
        public bool LogisticsBookDelete { get; set; }
        public bool LogisticsBookRead { get; set; }
        public bool LogisticsProfitSave { get; set; }
        public bool LogisticsProfitDelete { get; set; }
        public bool LogisticsProfitRead { get; set; }
        public bool LogisticsPFRead { get; set; }
        public bool LogisticsPaymentSave { get; set; }
        public bool LogisticsPaymentRead { get; set; }
        public bool InlandBookSave { get; set; }
        public bool InlandBookDelete { get; set; }
        public bool InlandBookRead { get; set; }
        public bool InlandProfitSave { get; set; }
        public bool InlandProfitDelete { get; set; }
        public bool InlandProfitRead { get; set; }
        public bool InlandPaymentSave { get; set; }
        public bool InlandPaymentRead { get; set; }
        public bool ProjectBookSave { get; set; }
        public bool ProjectBookDelete { get; set; }
        public bool ProjectBookRead { get; set; }
        public bool ProjectProfitSave { get; set; }
        public bool ProjectProfitDelete { get; set; }
        public bool ProjectProfitRead { get; set; }
        public bool ProjectPaymentSave { get; set; }
        public bool ProjectPaymentRead { get; set; }
        public bool ExpresProfitTableRead { get; set; }
        public bool AirProfitTableRead { get; set; }
        public bool SeaLCLProfitTableRead { get; set; }
        public bool SeaFCLProfitTableRead { get; set; }
        public bool ExpressCostFProfit { get; set; }
        public bool ExpressCostDProfit { get; set; }
        public bool ExpressCostRProfit { get; set; }
        public bool AirExpCostFProfit { get; set; }
        public bool AirExpCostDProfit { get; set; }
        public bool AirExpCostRProfit { get; set; }
        public bool AirImpCostFProfit { get; set; }
        public bool AirImpCostDProfit { get; set; }
        public bool AirImpCostRProfit { get; set; }
        public bool SeaLCLExpCostFProfit { get; set; }
        public bool SeaLCLExpCostDProfit { get; set; }
        public bool SeaLCLExpCostRProfit { get; set; }
        public bool SeaLCLImpCostFProfit { get; set; }
        public bool SeaLCLImpCostDProfit { get; set; }
        public bool SeaLCLImpCostRProfit { get; set; }
        public bool SeaFCLExpCostFProfit { get; set; }
        public bool SeaFCLExpCostDProfit { get; set; }
        public bool SeaFCLExpCostRProfit { get; set; }
        public bool SeaFCLImpCostFProfit { get; set; }
        public bool SeaFCLImpCostDProfit { get; set; }
        public bool SeaFCLImpCostRProfit { get; set; }
        public bool SeaCSLExpCostFProfit { get; set; }
        public bool SeaCSLExpCostDProfit { get; set; }
        public bool SeaCSLExpCostRProfit { get; set; }
        public bool SeaCSLImpCostFProfit { get; set; }
        public bool SeaCSLImpCostDProfit { get; set; }
        public bool SeaCSLImpCostRProfit { get; set; }
        public bool LogCostFProfit { get; set; }
        public bool LogCostDProfit { get; set; }
        public bool LogCostRProfit { get; set; }
        public bool InlCostFProfit { get; set; }
        public bool InlCostDProfit { get; set; }
        public bool InlCostRProfit { get; set; }
        public bool PjlCostFProfit { get; set; }
        public bool PjlCostDProfit { get; set; }
        public bool PjlCostRProfit { get; set; }
        public bool AirBookingRequestSave { get; set; }
        public bool AirBookingRequestRead { get; set; }
        public bool AirBookingRequestConfirmSave { get; set; }
        public bool AirBookingRequestConfirmRead { get; set; }
        public bool AdvancePaymentRead { get; set; }
        public bool AdvancePaymentSave { get; set; }
        public bool AccInvoiceSave { get; set; }
        public bool AccInvoiceDelete { get; set; }
        public bool AccInvoiceRead { get; set; }
        public bool AirPriceInput { get; set; }
        public bool ExpressPriceInput { get; set; }
        public bool SeaPriceInput { get; set; }
        public bool CompanyInfCtrl { get; set; }
        public bool DepartmentCltrl { get; set; }
        public bool PersonalDataCtrl { get; set; }
        public bool CustomerCtrl { get; set; }
        public bool AgentCtrl { get; set; }
        public bool SupplierCtrl { get; set; }
        public bool OtherContact { get; set; }
        public bool? ShipperCtrl { get; set; }
        public bool? ConsigneeCtrl { get; set; }
        public bool GeneralCtrl { get; set; }
        public bool? NameFeeControl { get; set; }
        public bool? ProfitRead { get; set; }
        public bool? DebtRecordRead { get; set; }
        public bool? PortIndexEdit { get; set; }
        public bool? ContainerManagement { get; set; }
        public bool? VehicleManagement { get; set; }
        public bool? VehicleNorm { get; set; }
        public bool? ProfitExchange { get; set; }
        public bool? AssetManagement { get; set; }
        public string RestrictInfo { get; set; }
        public string KeyLog { get; set; }
        public bool? AirExpfixedCostSave { get; set; }
        public bool? AirExpfixedCostRead { get; set; }
        public bool? AirExpfixedCostDelete { get; set; }
        public bool? AirImpfixedCostSave { get; set; }
        public bool? AirImpfixedCostRead { get; set; }
        public bool? AirImpfixedCostDelete { get; set; }
        public bool? LogfixedCostSave { get; set; }
        public bool? LogfixedCostRead { get; set; }
        public bool? LogfixedCostDelete { get; set; }
        public bool? ExpressfixedCostSave { get; set; }
        public bool? ExpressfixedCostRead { get; set; }
        public bool? ExpressfixedCostDelete { get; set; }
        public bool? InlandfixedCostSave { get; set; }
        public bool? InlandfixedCostRead { get; set; }
        public bool? InlandfixedCostDelete { get; set; }
        public bool? ProjectfixedCostSave { get; set; }
        public bool? ProjectfixedCostRead { get; set; }
        public bool? ProjectfixedCostDelete { get; set; }
        public bool? SeaCSLExpfixedCostSave { get; set; }
        public bool? SeaCSLExpfixedCostRead { get; set; }
        public bool? SeaCSLExpfixedCostDelete { get; set; }
        public bool? SeaLCLExpfixedCostSave { get; set; }
        public bool? SeaLCLExpfixedCostRead { get; set; }
        public bool? SeaLCLExpfixedCostDelete { get; set; }
        public bool? SeaCSLImpfixedCostSave { get; set; }
        public bool? SeaCSLImpfixedCostRead { get; set; }
        public bool? SeaCSLImpfixedCostDelete { get; set; }
        public bool? SeaFCLImpfixedCostSave { get; set; }
        public bool? SeaFCLImpfixedCostRead { get; set; }
        public bool? SeaFCLImpfixedCostDelete { get; set; }
        public bool? SeaLCLImpfixedCostSave { get; set; }
        public bool? SeaLCLImpfixedCostRead { get; set; }
        public bool? SeaLCLImpfixedCostDelete { get; set; }
        public bool? VoucherManagement { get; set; }
        public bool? AdvancePaymentDelete { get; set; }
        public bool? AcSOARead { get; set; }
        public bool? AcSOASave { get; set; }
        public bool? AcSOADelete { get; set; }
        public bool? ACPayroll { get; set; }
        public bool? LockShipment { get; set; }
        public bool? RestrictSELVCRead { get; set; }
        public bool? RestrictUNSELVCRead { get; set; }
        public bool? ChargesAC { get; set; }
        public bool? UpdateGainLoss { get; set; }
        public bool? DeniedIssueInv { get; set; }
        public bool? FormsManage { get; set; }
        public bool? DeniedCreateNewPN { get; set; }
        public bool? ViewBKCharges { get; set; }
        public bool? DeniedViewComm { get; set; }
        public bool? Leads { get; set; }
        public bool? Potential { get; set; }
        public bool? SalesIncentive { get; set; }
        public bool? RestrictDefaultCharges { get; set; }
        public bool? RestrictAR { get; set; }
        public bool? RestrictAP { get; set; }
        public bool? DocsRelease { get; set; }
        public bool? PartnerLCFieldsEditable { get; set; }
        public bool? POSave { get; set; }
        public bool? PORead { get; set; }
        public bool? PODelete { get; set; }
        public bool? BKRequestSave { get; set; }
        public bool? BKRequestRead { get; set; }
        public bool? BKRequestDelete { get; set; }
        public bool? PartnerENFieldsEditable { get; set; }
        public bool? SalesmanChange { get; set; }
        public bool? PartnerMNGFieldsEditable { get; set; }
        public bool? PartnerCreditTermFieldsEditable { get; set; }
        public bool? CargoReceiptSave { get; set; }
        public bool? CargoReceiptRead { get; set; }
        public bool? CargoReceiptDelete { get; set; }
        public bool? DeniedViewAirVendor { get; set; }
        public bool? DeniedViewSeaVendor { get; set; }
        public bool? DeniedExportMNReport { get; set; }
        public bool? DELETEHANDLINGTASK { get; set; }
        public bool? AdvanceSettlementCTRLRead { get; set; }
        public bool? AdvanceSettlementCTRLUpdate { get; set; }
        public bool ASSIGNOPSSTAFF { get; set; }
        public bool SENDEMAIL { get; set; }
        public bool? AcsCTRLUpdate { get; set; }
        public bool? PartnerAuth { get; set; }
        public bool? ShipmentPaymentCTRLUpdate { get; set; }
        public bool? AcSOAPayment { get; set; }
        public bool? AcsCTRLUnUpdate { get; set; }
        public bool? PartnersReadExport { get; set; }
        public bool? VCLock { get; set; }
        public bool? VCUnlock { get; set; }
        public bool? GroupListUpdate { get; set; }
        public bool? ALLUSERSDefaultCharges { get; set; }
        public bool? ChargesRequestApproval { get; set; }
        public bool? PersonalPartnerEditNonOwner { get; set; }
        public bool? BKCreatorProfitRead { get; set; }
        public bool? VoucherManagementDelete { get; set; }
        public bool? SALESRead { get; set; }
        public bool? SALESSave { get; set; }
        public bool? SALESDelete { get; set; }
        public bool? CSRead { get; set; }
        public bool? CSSave { get; set; }
        public bool? CSDelete { get; set; }
        public bool? TTRead { get; set; }
        public bool? TTSave { get; set; }
        public bool? TTDelete { get; set; }
        public bool? OPSRead { get; set; }
        public bool? OPSSave { get; set; }
        public bool? OPSDelete { get; set; }
        public bool? FNRead { get; set; }
        public bool? FNSave { get; set; }
        public bool? FNDelete { get; set; }
        public bool ACCESSKPIREPORT { get; set; }
        public bool IMPORTDOC { get; set; }
        public bool EXPORTDOC { get; set; }
        public bool GETBILLREPORT { get; set; }
        public bool? AssetManagementDelete { get; set; }

        public virtual ContactsList UserNameNavigation { get; set; }
    }
}
